#!/usr/bin/env ruby

#NOTE: you may need change file permissions
#      chmod +x hooks/update-version

exit 1 if ARGV.length == 0

version = ARGV[0]
version = version[1..-1]   # keep from character 1 onwards, e.g. v0.01.001 becomes 0.01.001

output = %{#{version}}

printf "%-25s : %s\n", "GEM VERSION", version
File.open("kversion", "w+") {|f| f.write(output) }
